# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='agent_dup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentdup', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf2txt_dup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfdup', to='document.Document'),
        ),
    ]
